{
    "Message": "Download in progress...",
    "CompletionMessage": "Download Successful",
    "CompletionTimeout": 7,
    "OnSuccess": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/DownloadOffline.action",
    "_Type": "Action.Type.ProgressBanner"
}