{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/SyncFailureMessage.action",
	"OnSuccess": "/Attendance_List/Rules/CAP_SERVICE_SF_LMS/ErrorArchive_CheckForSyncError.js",
	"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
	"DefiningRequests": [
		{
			"Name": "cust_Alunos",
			"Query": "cust_Alunos",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_Cursos",
			"Query": "cust_Cursos",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_Instrutores",
			"Query": "cust_Instrutores",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_Locais",
			"Query": "cust_Locais",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_Turmas",
			"Query": "cust_Turmas?$expand=cust_ListaNav($expand=cust_AlunosNav),cust_CursosNav,cust_Inst1Nav,cust_Inst2Nav&$filter=cust_LMS ne 'S' or cust_LMS eq null and cust_Status ne 'cancelada' or cust_Status eq null",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_ListadePresenca",
			"Query": "cust_ListadePresenca?$expand=cust_AlunosNav",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_listadiaria",
			"Query": "cust_listadiaria",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "cust_presencalms",
			"Query": "cust_presencalms",
			"AutomaticallyRetrievesStreams": false
		}
	]
}