{
	"_Type": "Action.Type.ProgressBanner",
	"OnFailure": "/Attendance_List/Actions/GenericMessageBox.action",
	"OnSuccess": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/UploadOffline.action",
	"Message": "Upload in progress...",
	"CompletionMessage": "Sync completed",
	"CompletionTimeout": 7
}