{
	"_Type": "Action.Type.PopoverMenu",
	"PopoverItems": [
		{
			"Enabled": true,
			"Icon": "sap-icon://synchronize",
			"OnPress": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/SyncStartedMessage.action",
			"Title": "Sync Changes",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://headset",
			"OnPress": "/Attendance_List/Actions/Application/NavToSupport.action",
			"Title": "Support",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://refresh",
			"OnPress": "/Attendance_List/Actions/Application/AppUpdateProgressBanner.action",
			"Title": "Check for Updates",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://hint",
			"OnPress": "/Attendance_List/Actions/Application/NavToAbout.action",
			"Title": "About",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://reset",
			"OnPress": "/Attendance_List/Actions/Application/ResetMessage.action",
			"Title": "Reset",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://log",
			"OnPress": "/Attendance_List/Actions/Application/Logout.action",
			"Title": "Logout",
			"Visible": "/Attendance_List/Rules/Application/ClientIsMultiUserMode.js"
		},
		{
			"Title": "Logs",
			"Icon": "sap-icon://document-text",
			"OnPress": "/Attendance_List/Actions/Application/NavToActivityLog.action",
			"Visible": true,
			"Enabled": true,
			"Styles.Title": ""
		},
		{
			"Title": "Download",
			"Icon": "sap-icon://synchronize",
			"OnPress": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/DownloadOffline.action",
			"Visible": true,
			"Enabled": true,
			"Styles.Title": "",
			"Styles.Icon": "",
			"TextAlignment": "Center"
		},
		{
			"Title": "Upload",
			"Icon": "sap-icon://synchronize",
			"TextAlignment": "Center",
			"Styles": {
				"Title": "",
				"Icon": ""
			},
			"OnPress": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/UploadOffline.action",
			"Visible": true,
			"Enabled": true
		}
	]
}