{
	"_Type": "Action.Type.PopoverMenu",
	"PopoverItems": [
		{
			"Title": "Sincronizar",
			"Icon": "sap-icon://synchronize",
			"Style": "",
			"OnPress": "/Attendance_List/Actions/CAP_SERVICE_SF_LMS/Service/SyncStartedMessage.action",
			"Visible": true,
			"Enabled": true
		},
		{
			"Title": "Suporte",
			"Icon": "sap-icon://headset",
			"Style": "",
			"OnPress": "/Attendance_List/Actions/Application/SupportMenuPopover.action",
			"Visible": true,
			"Enabled": true
		},
		{
			"Title": "Incluir Turma",
			"Icon": "sap-icon://add",
			"Style": "",
			"Visible": true,
			"Enabled": true,
			"OnPress": "/Attendance_List/Actions/Teams/NavToTeamCreate.action"
		},
		{
			"Title": "Upload",
			"Icon": "sap-icon://upload",
			"Style": "",
			"Visible": true,
			"Enabled": true,
			"rawValue": ""
		}
	]
}