{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "ClosePresenceList"
	},
	"Target": {
		"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
		"EntitySet": "cust_ListadePresenca",
		"QueryOptions": "$filter=cust_Turma eq '{externalCode}'"
	}
}