{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "CreateEntityTeam"
	},
	"Target": {
		"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
		"EntitySet": "cust_Turmas"
	},
	"Properties": {
		"externalCode": "",
		"cust_ACT_CPNT_ID": "#Control:FormCellListPickerCurse/#SelectedValue",
		"cust_END_TME": "#Control:FormCellDatePickerEndDate/#Value",
		"cust_INST_ID1": "#Control:FormCellListPickerInstructor1/#SelectedValue",
		"cust_INST_ID2": "#Control:FormCellListPickerInstructor2/#SelectedValue",
		"cust_LOCN_DESC": "#Control:FormCellListPickerLocale/#Value/#First/DisplayValue",
		"cust_LOCN_ID1": "#Control:FormCellListPickerLocale/#SelectedValue",
		"cust_SSG_SEG_NUM": "#Control:FormCellSimplePropertyWorkload/#Value",
		"cust_START_TME": "#Control:FormCellDatePickerStartDate/#Value",
		"externalName": "#Page:TeamCreate/#Control:FormCellSimplePropertyTeamDescription/#Value"
	}
}