{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "CreatePresencalmsEntity"
	},
	"Target": {
		"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
		"EntitySet": "cust_presencalms"
	},
	"Properties": {
		"externalCode": ""
	}
}