{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavToTeamCreate"
	},
	"OnSuccess": "/Attendance_List/Rules/Main/SetUserIds.js",
	"PageToOpen": "/Attendance_List/Pages/Teams/TeamCreate.page"
}