{
	"_Type": "Action.Type.PopoverMenu",
	"ActionResult": {
		"_Name": "PopoverTeamEdit"
	},
	"PopoverItems": [
		{
			"Title": "Cancelar Turma",
			"Icon": "sap-icon://delete",
			"OnPress": "/Attendance_List/Actions/Teams/CancelTeamMessage.action",
			"Visible": true,
			"Enabled": true,
			"Styles": {
				"Title": "letter-color"
			}
		},
		{
			"Title": "Encerrar Turma",
			"Icon": "sap-icon://save",
			"TextAlignment": "",
			"Styles": {
				"Title": "letter-color",
				"Icon": ""
			},
			"OnPress": "/Attendance_List/Actions/Teams/CloseTeamMessage.action",
			"Visible": true,
			"Enabled": true
		}
	]
}