{
	"_Type": "Action.Type.PopoverMenu",
	"ActionResult": {
		"_Name": "PopoverTeamEdit"
	},
	"PopoverItems": [
		{
			"Title": "Salvar Turma",
			"Icon": "sap-icon://save",
			"Styles": {
				"Title": "letter-color"
			},
			"OnPress": "/Attendance_List/Rules/Teams/SaveEdit.js",
			"Visible": true,
			"Enabled": true
		},
		{
			"Title": "Excluir Turma",
			"Icon": "sap-icon://delete",
			"Styles": {
				"Title": "letter-color"
			},
			"OnPress": "/Attendance_List/Rules/Teams/Delete.js",
			"Visible": true,
			"Enabled": true
		}
	]
}