{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateTeam"
	},
	"Target": {
		"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
		"EntitySet": "cust_Turmas",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"externalCode": "{externalCode}",
		"cust_END_TME": "/Attendance_List/Rules/Teams/FormatEndDate.js",
		"cust_INST_ID2": "#Page:TeamEdit/#Control:FormCellListPicker2/#SelectedValue",
		"cust_START_TME": "/Attendance_List/Rules/Teams/FormatStartDate.js"
	},
	"RequestOptions": {
		"UpdateMode": "PATCH"
	}
}