{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateTeam"
	},
	"Target": {
		"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
		"EntitySet": "cust_ListadePresenca",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"externalCode": "{externalCode}"
	},
	"RequestOptions": {
		"UpdateMode": "PATCH"
	}
}