{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateTeam"
	},
	"Target": {
		"Service": "/Attendance_List/Services/CAP_SERVICE_SF_LMS.service",
		"EntitySet": "cust_Turmas",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"externalCode": "{externalCode}",
		"cust_END_TME": "#Control:FormCellDatePicker1/#Value",
		"cust_START_TME": "#Control:FormCellDatePicker0/#Value"
	},
	"RequestOptions": {
		"UpdateMode": "PATCH"
	}
}